steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/chess-backend:latest',
      '-f', 'backend/Dockerfile',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/chess-backend:latest'
timeout: '1200s'
