version: '3.8'

services:
  chess-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: chess-backend
    environment:
      - PORT=8080
    expose:
      - "8080"

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - chess-backend
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend:/srv/frontend:ro
