# fly.toml file generated for Fly.io deployment
app = "chess-backend"
# Change "chess-backend" above to your desired Fly.io app name

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # Use the existing backend/Dockerfile
  dockerfile = "backend/Dockerfile"

[env]
  # Cloud will set PORT automatically, but we default it here
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  ## HTTP port
  [[services.ports]]
    port = 80
  ## HTTPS port (with TLS automatically managed)
  [[services.ports]]
    port = 443
    handlers = ["tls"]

  # Tune concurrency to share your single vCPU across multiple connections
  [[services.concurrency]]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  # Optional health check
  [[services.http_checks]]
    path = "/"
    interval = 10
    timeout = 2
    method = "get"
